name: string_equation
description: ConditionEquation is a powerful Dart package that allows you to dynamically evaluate both logical and mathematical expressions from a string format. It offers robust support for variables, making it highly useful in scenarios where you need to parse, interpret, and compute expressions programmatically. Whether you're working on rule engines, dynamic forms, or data validation, ConditionEquation simplifies the process of handling complex expressions in your Dart applications.
version: 1.0.0
repository: https://github.com/dexterTalha/string_equation.git

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  intl: ^0.19.0
  vector_math: ^2.1.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
